# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- garth-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
- jekyll-paginate

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: pretty  # Permalink style (/YYYY/MM/DD/page-name/)
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: FreezyPeaz # Needed for Siteleaf
    output: true
    description: "The name ‘freezypeaz’ came to me reminiscing through my mind and remembering a silly memory where I found myself struggling to open a bag of frozen peas. At the time, I was going through a rough patch and had a hard time expressing my emotions and instead bottled them up and was often overthinking my actions. Those thoughts intensified my then frustration, leading to the bag of peas ripping in half with peas flying everywhere around the kitchen. Instead of anger, for some reason, I found the situation quite ironic and even felt relief. Similarly to the peas stuck together in a block of ice, I had to find a way to express my emotions little by little, so that I don’t end up like the bag. So, in summary, with each story, I’ll open my metaphorical bag of peas and offer one in exchange for some peace of mind. I hope you enjoy this exploration of my thoughts in this blog and enjoy your virtual warm bowl of emotional peas!" # The post list page content

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "FreezyPeaz" # Site name or title
logo: "/assets/logo.svg" # Site logo
# favicon: "/favicon.ico" # Uncomment to add custom favicon, or leave as is to use site logo
description: "" # Site description and default description
url: "https://freezypeaz.com" # Site url
baseurl: ""
lang: en-GB
